const loginJS = require('./index');

const loginConfig = {
	mongodbURI: process.env.MONGODB_URI,
	jwtSecret: process.env.JWT_SECRET,
};

// Optional
// loginConfig.passwordLength = parseInt(process.env.ACCOUNT_PWD_LENGTH); // positive integer
// loginConfig.jwtSessionExpiration = parseInt(process.env.JWT_SESSION_EXPIRATION); // in seconds

const resetConfig = {
	jwtResetSecret: process.env.JWT_RESET_SECRET,
	emailFromUser: process.env.EMAIL_FROM_USER,
	emailFromPass: process.env.EMAIL_FROM_PASS,
	emailToUser: process.env.EMAIL_TO_USER,
	emailHost: process.env.EMAIL_HOST,
	emailPort: process.env.EMAIL_PORT,
	emailSecure: process.env.EMAIL_SECURE,
};

// Optional
// resetConfig.jwtResetExpiration = parseInt(process.env.JWT_RESET_EXPIRATION) // in seconds
// resetConfig.emailHeading = 'Blackswan Media Group';
// resetConfig.emailSubjectLine = 'Reset Password';
// resetConfig.emailMessage = 'Custom reset password message goes here. Reset password link will be autogenerated.';

loginJS(loginConfig, resetConfig);